Note/urls.py
from django.urls import path
from . import views

app_name = 'Note'
urlpatterns = [
    path("", views.index, name='index'),
    path("category/<category>", views.category, name='category'),
    path("details/<note_id>", views.details, name='details'),
    path("logout", views.logout_view, name='logout'),
    path("login_validate", views.login_validate, name='login_validate'),
    path("login", views.login_view, name='login_page'),
    path("post_note", views.post_note, name='post_note'),
    path("new_note", views.post_page, name='new_note'),
    path("serach_note", views.search_note, name='search_note'),
    path("edit_page/<note_id>", views.edit_page, name='edit_page'),
    path("edit_note", views.edit_note, name='edit_note'),
    path("register", views.register_view, name='register_page'),
    path("register_account", views.register_account, name='register_account'),
    path("open/<path>/<file>", views.open_file, name='open')
]

NoteUp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('note/', include('Note.urls')),
    path('admin/', admin.site.urls),
]

Note/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    category = models.CharField(max_length=100)
    text = models.TextField(max_length=3000)
    modification_date = models.DateTimeField('date_modified')

    def __str__(self):
        return str(self.title) + ' (' + str(self.category) + ')'


class File(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    file = models.FileField(upload_to="note_files")

    def __str__(self):
        return str("file_" + str(self.id))

Note/views.py
from django.contrib.auth.models import User
from django.utils import timezone

from .functions import handle_file
from .models import Note, File
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, logout, login
from django.http import Http404, HttpResponse, FileResponse
from .functions import check

from NoteUp.settings import MEDIA_ROOT


def index(request):
    if request.user.is_authenticated:
        notes = Note.objects.filter(user=request.user).order_by('-modification_date')
        categories_list = notes.values_list('category', flat=True).distinct().order_by()
        return render(request, 'Note/index.html', context={
            'user': request.user, 'notes': notes, 'categories': categories_list
        })
    else:
        return redirect('Note:login_page')


def category(request, category):
    if request.user.is_authenticated:
        notes = Note.objects.filter(user=request.user, category=category)
        if notes:
            return render(request, 'Note/category.html', context={'notes': notes, 'category': category})
        else:
            raise Http404('Page not found')
    else:
        return redirect('Note:login_page')


def details(request, note_id):
    if request.user.is_authenticated:
        note = Note.objects.filter(pk=note_id, user=request.user)
        if note:
            files = File.objects.filter(note=note[0])
            return render(request, 'Note/details.html', context={'note': note[0], 'files': files})
        else:
            raise Http404('Page not found')
    else:
        return redirect('Note:login_page')


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        return render(request, 'Note/logout.html')
    else:
        raise Http404('Page not found')


def login_view(request):
    return render(request, 'Note/login.html')


def login_validate(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('Note:index')
    else:
        return render(request, 'Note/login.html', context={'message': 'Bad username or password'})


def register_view(request):
    if request.user.is_authenticated:
        logout(request)
    return render(request, 'Note/register.html')


def register_account(request):
    username = request.POST['username']
    password = request.POST['password']
    email = request.POST['email']
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']

    if email and username and password and first_name and last_name:
        if not check(email):
            return render(request, "Note/register.html", context={'email_message': "Invalid email :/"})
        user = User.objects.create_user(username, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        logout(request)
        login(request, user)
        return redirect('Note:index')
    else:
        return render(request, "Note/register.html", context={'message': "Missing some information :/"})


def post_note(request):
    if request.user.is_authenticated and request.method == 'POST':
        user = User.objects.get(pk=request.user.id)
        title = request.POST['title']
        text = request.POST['text']
        category = request.POST['category']
        mod_date = timezone.now()

        if title and text and category:
            note = Note.objects.create(user=user, title=title, text=text, category=category, modification_date=mod_date)

            if request.FILES:
                handle_file(file=request.FILES['myfile'], note=note)

            return redirect('Note:details', note_id=note.id)
        else:
            return redirect('Note:new_note')
    else:
        return redirect('Note:login_page')


def edit_note(request):
    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.id)
        note_id = request.POST['id']
        title = request.POST['title']
        text = request.POST['text']
        category = request.POST['category']
        mod_date = timezone.now()

        note = get_object_or_404(Note, user=user, pk=note_id)
        if title and text and category:
            note.title = title
            note.category = category
            note.modification_date = mod_date
            note.text = text
            note.save()

            if request.FILES:
                handle_file(file=request.FILES['myfile'], note=note)

            return redirect('Note:details', note_id=note.id)
        else:
            return redirect('Note:new_note')
    else:
        return redirect('Note:login_page')


def post_page(request):
    return render(request, 'Note/new_note.html')


def edit_page(request, note_id):
    if request.user.is_authenticated:
        note = get_object_or_404(Note, pk=note_id, user=request.user)
        return render(request, 'Note/new_note.html', context={'note': note, 'edit': True})
    else:
        return redirect('Note:login_page')


def search_note(request):
    if request.user.is_authenticated:
        search_value = request.POST['value']
        notes = Note.objects.filter(user=request.user, title__contains=search_value).order_by('-modification_date')
        categories_list = notes.values_list('category', flat=True).distinct().order_by()
        return render(request, 'Note/index.html', context={
            'user': request.user, 'notes': notes, 'categories': categories_list
        })
    else:
        return redirect('Note:login_page')


def open_file(reqeust, path, file):
    if reqeust.user.is_authenticated:
        notes = Note.objects.filter(user=reqeust.user)
        for note in notes:
            if File.objects.filter(note=note, file=path+"/"+file):
                return FileResponse(open(MEDIA_ROOT + "\\" + path + "\\" + file, 'rb'))

    return redirect('Note:login_page')

Note/templates/Note/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{category}}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Note/style.css' %}">
</head>
<body>
    <div id="user_logout">
            <h3>Welcome {{user.username}} / <a href="{% url 'Note:logout' %}">Log out</a></h3>
    </div>
    <table style="margin: auto; border: 1px solid gray; width: 25%;">
        <thead style="margin: auto; font-family: 'Courier New', Courier, monospace; border: 1px solid gray;">
            <tr style="font-size: 20pt; background-color: rgb(88, 88, 88); color: black;">
                <td style="text-align: center;">Notes</td>
            </tr>
        </thead>
        <tbody>
            {% for note in notes %}
            <tr>
                <td style="height: 30px;">
                    <a href="{% url 'Note:details' note.id%}" style="margin-left: 20px;">{{note}}</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div style="margin: auto; text-align: center; font-size: 15pt;">
         <a href="{% url 'Note:index' %}" style="text-decoration: none;"> ⮪ Back</a>
    </div>

</body>
</html>

Note/templates/Note/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ note.title }}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Note/style.css' %}">
</head>
<body>
    <div id="user_logout">
            <h3>Welcome {{user.username}} / <a href="{% url 'Note:logout' %}">Log out</a></h3>
    </div>

    <div style="margin: 10%; margin-top: 1%;">
        <div >
            <h1>{{ note.title }}<a href="{% url 'Note:edit_page' note.id %}" style="float: right;">Edit</a></h1>

        </div>
        <br>
        <h4>{{ note.modification_date }}</h4>
        <h5><a href="{% url 'Note:category' note.category %}">{{ note.category }}</a></h5>
        <p>{{ note.text }}</p>
        <br>
        {% for file in files %}
            <a href="/note/open{{ file.file.url }}" target="_blank" style="margin-left: 10px; font-size:10pt;"> {{ file }} </a> <br>
        {% endfor %}
        <br><br>
        <a href="{% url 'Note:index' %}" style="text-decoration: none;">⮪ Back</a>
    </div>
</body>
</html>

Note/templates/Note/index.html
<!DOCTYPE html>
<html lang="en">
    <head >
        <meta charset="utf-8">
        <title>Notes {{ user.username }}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'Note/style.css' %}">
    </head>
    <body>
        <div>
            <div id="user_logout">
                <h3>
                    Welcome {{user.username}} /
                    <a href="{% url 'Note:logout' %}" style="">
                        Log out
                    </a>
                </h3>
            </div>
            <div id="categories">
                <table style="float: left; border: gray 1px solid; margin-left: 7%; ">
                    <thead style="font-size: 20pt; background-color: rgb(88, 88, 88); padding: 1%;" >
                        <tr>
                            <th width=180px>Categories</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for category in categories %}
                            <tr>
                                <td class="cat_item"><a  style="margin-left: 20px;" href="{% url 'Note:category' category %}"> {{ category }} </a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div style="float: left; margin-left: 10%;">
                <table style="margin: auto; font-family: 'Courier New', Courier, monospace; border: 1px solid gray; ">
                    <thead style="font-size: 20pt; background-color: rgb(88, 88, 88); color: black;">
                        <tr>
                            <th width="250px">Title</th>
                            <th width="180px">Category</th>
                            <th width="250px" >Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for note in notes%}
                        <tr>
                            <td><a href="{% url 'Note:details' note.id %}">{{ note.title }}</a></td>
                            <td><a href="{% url 'Note:category' note.category %}">{{ note.category }}</a></td>
                            <td style="color: gray;">{{ note.modification_date }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div id="search_and_new_button">
                <div id="new_note_button">
                    <a href="{% url 'Note:new_note' %}">
                        New note
                    </a>
                </div>
                <br>
                <div id="search_note" style="">
                    <form action="{% url 'Note:search_note' %}" method="post">
                        {%csrf_token%}
                        <input type="search" placeholder="Search" name="value" style="float: left;">
                        <input type="submit" value="Search" style="float: left;">
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

Note/templates/Note/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login page</title>
    <style>
        #form_div {
            margin: 40%;
            margin-top: 10%;
            width: 20%;
        }

        input {
            float: right;
            margin-left: 4%;
            border: solid 1px gray;
            margin-bottom: 1%;
            background-color: rgb(78, 78, 78);
            font-size: 14pt;
        }

    </style>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Note/style.css' %}">
</head>
<body>
    <div id="form_div">
        <h2>Log in</h2>
        <form action="login_validate" method="post">
            {%csrf_token%}
            <label>Username</label>
            <input name="username" type="text">
            <br><br>
            <label>Password</label>
            <input name="password" type="password">
            <br><br><a href="{% url 'Note:register_page' %}">Register account</a>
            <input type="submit" value="Log in">
            {% if message %}
            <h1> {{ message }}</h1>
            {% endif %}
        </form>
    </div>

</body>
</html>

Note/templates/Note/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logged out</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Note/style.css' %}">
</head>
<body>
    You've been logged out
    <a href="{% url 'Note:login_page' %}">Click here to log in again</a>
</body>
</html>

Note/templates/Note/new_note.html
<!DOCTYPE html>
<html lang="en">
    <head >
        <meta charset="utf-8">
        <title>Notes {{ user.username }}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'Note/style.css' %}">
    </head>
    <body style="margin: 0px;">
        <div id="user_logout" style="border: solid 1px gray; margin-bottom: 3%; background-color: rgb(78, 78, 78);">
            <h3 style="color: black;">
                Welcome {{user.username}} /
                <a href="{% url 'Note:logout' %}" style="margin-right:20px">
                    Log out
                </a>
            </h3>
        </div>
        <div style="margin-left: 20%; width: 60%; font-size: 18pt;">
            {% if note %}
                <form action="{% url 'Note:edit_note' %}" method="post" id="post_form" enctype="multipart/form-data">
                {% csrf_token %}
                <label> Title: </label>
                <input name="id" value="{{ note.id}}" style="visibility: hidden; width:0;" >
                <input name="title" type="text" required="True" style="margin-left: 2%;
                                                                       border: solid 1px gray;
                                                                       margin-bottom: 1%;
                                                                       background-color: rgb(78, 78, 78);
                                                                       font-size: 18pt;" value="{{ note.title }}">
                <input type="submit" value="Post" style="float: right;
                                                        background-color:
                                                        rgb(85, 85, 85);
                                                        border: 1px solid gray;
                                                        color: black;
                                                        font-family: 'Courier New', Courier, monospace;
                                                        font-size: 15pt;
                                                        text-decoration: none;
                                                        font-weight: bold;
                                                        font-size: 25pt;">
                <br>
                <label> Category: </label>

                <input name="category" type="text" required="True" style="margin-left: 2px;
                                                                          border: solid 1px gray;
                                                                          margin-bottom: 3%;
                                                                          background-color: rgb(78, 78, 78);
                                                                          font-size: 18pt;" value="{{ note.category }}">
                <br>
                <input type="file"  name="myfile" multiple>
                <br><br>
            </form>
            <textarea form="post_form" rows="20" cols="100" name="text" style="width: 100%;
                                                          border: solid 1px gray;
                                                          margin-bottom: 3%;
                                                          background-color: rgb(78, 78, 78);
                                                          font-size: 18pt">{{ note.text }}
            </textarea>
            {% else %}
            <form action="{% url 'Note:post_note' %}" method="post" id="post_form" enctype="multipart/form-data">
                {% csrf_token %}
                <label> Title: </label>
                <input name="title" type="text" required="True" style="margin-left: 4%;
                                                                       border: solid 1px gray;
                                                                       margin-bottom: 1%;
                                                                       background-color: rgb(78, 78, 78);
                                                                       font-size: 18pt;">
                <input type="submit" value="Post" style="float: right;
                                                        background-color:
                                                        rgb(85, 85, 85);
                                                        border: 1px solid gray;
                                                        color: black;
                                                        font-family: 'Courier New', Courier, monospace;
                                                        font-size: 15pt;
                                                        text-decoration: none;
                                                        font-weight: bold;
                                                        font-size: 25pt;">

                <br><br>
                <label> Category: </label>
                <input name="category" type="text" required="True" style="margin-left: 2px;
                                                                          border: solid 1px gray;
                                                                          margin-bottom: 3%;
                                                                          background-color: rgb(78, 78, 78);
                                                                          font-size: 18pt;">
                <br>
                <input type="file" name="myfile"  multiple>
                <br><br>
            </form>
            <textarea form="post_form" rows="20" cols="100" name="text" style="width: 100%;
                                                          border: solid 1px gray;
                                                          margin-bottom: 3%;
                                                          background-color: rgb(78, 78, 78);
                                                          font-size: 18pt">Enter note here...
            </textarea>
            {% endif %}
            <div style="margin: auto; text-align: center; font-size: 15pt;">
                <a href="{% url 'Note:index' %}" style="text-decoration: none;"> ⮪ Home</a>
            </div>
        </div>
    </body>
</html>

Note/templates/Note/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <style>
        #form_div {
            margin: 40%;
            margin-top: 10%;
            width: 20%;
        }

        input {
            float: right;
            margin-left: 4%;
            border: solid 1px gray;
            margin-bottom: 1%;
            background-color: rgb(78, 78, 78);
            font-size: 14pt;
        }


    </style>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Note/style.css' %}">
</head>
<body>
    <div id="form_div">
        <h1>Register: </h1>
        <form action="{% url 'Note:register_account' %}" method="post">
            {% csrf_token %}
            <label>Frist name: </label>
            <input type="text" name="first_name">
            <br><br>
            <label>Last name: </label>
            <input type="text" name="last_name">
            <br><br>
            <label>Username: </label>
            <input type="text" name="username">
            <br><br>
            {% if email_message %}
            <h2>Invalid emial</h2>
            {% endif %}
            <label>E-mail: </label>
            <input type="text" name="email">
            <br><br>
            <label>Password: </label>
            <input type="password" name="password">
            <br><br>
            <input type="submit" value="Register" style="margin-right: 40%;">
        </form>
            {% if message %}
            <h2>Missing information</h2>
            {% endif %}
    </div>
</body>
</html>